# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_kotlin_version=1.13.12+kotlin.2.4.0

# Mod Properties
mod_version=1.5.11+26.2
maven_group=me.cael
archives_base_name=capes

# Dependencies
fabric_api_version=0.152.1+26.2

# Publishing
curseforge_id=408481
modrinth_id=89Wsn8GD